version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - '27018:27017'
    volumes:
      - meta-nest-dev-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}

  mongo-express:
    image: mongo-express:0.54
    depends_on:
      - mongo
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASSWORD}
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    ports:
      - '6082:8081'
    volumes:
      - meta-nest-dev-db:/data/db

  meilisearch:
    image: getmeili/meilisearch:latest
    ports:
      - "7700:7700"
    environment:
      - MEILI_MASTER_KEY=${DEV_KEY}
      - MEILI_NO_ANALYTICS=false
    volumes:
      - meta-nest-dev-ms:/data.ms

volumes:
  meta-nest-dev-db:
  meta-nest-dev-ms:
